### ISSUE TITLE
In dark mode, placeholder text in "New Deck" cards are too dark to see well against dark background

### ISSUE THREAD

**Issue by imanischult** [flashcards/flashcards.github.io#2]
Problem: Placeholder text in "New Deck" cards are too dark to see against dark background
Desired Result: Change font to lighter text when in dark mode
Example:
![image](https://user-images.githubusercontent.com/47801956/93647290-12167280-f9d6-11ea-89d3-0742f5267e17.png)

**Comment by zlawson-ut** [comment]
Hi @imanischult, thanks for brining this to our attention. This has been added to our list of things to address in our next release, stay tuned! If you have any other feedback feel free to contact me directly via zachary at flashcards.io.
