### ISSUE TITLE
Flashcards too small

### ISSUE THREAD

**Issue by codingForCats** [flashcards/flashcards.github.io#6]
Maybe it's because I'm using a 2k monitor, but the iframe with the flashcards is too small. The text itself seems fine, it's just the box making everything cluttered

Thanks for the cards btw

**Comment by zlawson-ut** [comment]
Thanks for this feedback @codingForCats. Are you using the flashcards that are [embedded on flashcards.github.io](https://flashcards.github.io/graphql/introduction.html) or the ones on [flashcards.io](https://flashcards.io/app/?url=https://www.codecademy.com/learn/fscj-22-algorithms/modules/wdcp-22-merge-sort-8c032673-eb72-45a9-9ec9-99db73aa5f8d/cheatsheet)?
