### ISSUE TITLE
Command Line Flashcard Screen Not adjusting properly 

### ISSUE THREAD

**Issue by spekkiodancer** [flashcards/flashcards.github.io#7]
The command line page is not working properly. I found the solution: 

On `command_line/introduction.html` on line 276  `<iframe src="https://embed.flashcards.io/?url=https://flashcards.github.io/command_line/introduction.html"></iframe>` 

is missing the `class="FlashcardsIO" ` class. So, it needs to be:

 `<iframe class="FlashcardsIO" src="https://embed.flashcards.io/?url=https://flashcards.github.io/command_line/introduction.html"></iframe>` 

 I cannot commit to this repo.

**Comment by zlawson-ut** [comment]
Hello @spekkiodancer, thank you so much for catching this!

If you're looking to commit to the repository, please open a [pull request](https://github.com/flashcards/flashcards.github.io/compare/master...spekkiodancer:flashcardsplus.github.io:master). You can find detailed instructions on the [contributing.md](https://github.com/zachlawsonx/flashcards.github.io/blob/master/CONTRIBUTING.md) page. For more comprehensive guidance, check out TheOdinProject's instructions [here](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#setting-up-your-local-clone). Feel free to reach out if you run into any challenges – I'm here to help!
